# Generated by Django 4.0.4 on 2022-06-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'USER PROFILES'},
        ),
    ]
