# Generated by Django 4.0.4 on 2022-06-25 11:47

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='avatar.png', upload_to=users.models.user_profile_path),
        ),
    ]
