# Generated by Django 4.0.4 on 2022-06-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRA', 'DRAFT'), ('PUB', 'PUBLISHED')], default='DRA', max_length=10),
        ),
    ]
